#!/bin/python

import os
name='VA_FAIRFAX'
print('2016 election')
os.system('grep %s county_votes/2016_votes.dat'%name)
print('Per Capita Income')
os.system('grep %s avg_income/per_capita_income.csv'%name)
print('Uninsured Per')
os.system('grep %s avg_income/uninsured_rate3.dat'%name)
print('Some College Per')
os.system('grep %s avg_income/some_college.dat'%name)
print('AF Amer Per')
os.system('grep %s race/afamer_per.dat'%name)
print('White Per')
os.system('grep %s race/white_per.dat'%name)
print('Asian Per')
os.system('grep %s race/asian_per.dat'%name)
print('Hispanic Per')
os.system('grep %s race/hispanic_per.dat'%name)
print('Seniors Per')
os.system('grep %s age/per_above_65.dat'%name)
print('Poverty Rate')
os.system('grep %s avg_income/poverty_rate.dat'%name)
print('Income Inequality')
os.system('grep %s avg_income/income_inequality.dat'%name)
print('Unemployment Rate')
os.system('grep %s avg_income/unemployment_rate.dat'%name)
print('Rural Per')
os.system('grep %s living/rural_pop.dat'%name)
print('Citizens Per')
os.system('grep %s race/citizenship.dat'%name)
